### ISSUE TITLE
tomcat9.0.64未成功

### ISSUE THREAD

**Issue by jielansudo** [veo/wsMemShell#1]
访问路径127.0.0.1:8080/examples/wscmd.jsp?path=/x 后未成功注入websocks服务，无法连接127.0.0.1:8080/examples/x。

**Comment by veo** [comment]
> 访问路径127.0.0.1:8080/examples/wscmd.jsp?path=/x 后未成功注入websocks服务，无法连接127.0.0.1:8080/examples/x。

127.0.0.1:8080/x

**Comment by jielansudo** [comment]
127.0.0.1:8080/x 这个也是一样的连接不上，尝试过了。

**Comment by veo** [comment]
> 127.0.0.1:8080/x 这个也是一样的连接不上，尝试过了。
9.0.64版本测试没问题
![image](https://user-images.githubusercontent.com/38176360/176811278-7d4add92-379e-401a-a930-26d8478d3ad8.png)

可能是其他问题，比如用了nginx或者cdn反代，没有支持websocket协议也会连不上
