### ISSUE TITLE
你好！我想问下执行命令情况下中文乱码有没办法解决和一些其他问题

### ISSUE THREAD

**Issue by Chinakentgao** [veo/wsMemShell#10]
我拿测试环境试了一下发现，中文的内容返回都是乱码。还有websocket client有没有windows版本的，用bp发包和插件都不太方便。bp构造ws请求时path部分不知道怎么构造，只能抓插件的包拿来用。也挺头疼的！关于java的文件的利用，由于我对内存马不是特别了解，通常搭配的应该类似jndi注入这种来用。但是注入成功后如何调用就不太清楚，没有测试过。

**Comment by veo** [comment]
抱歉，你的问题我一时半会没办法回答。我尽可能的回答部分

1.burp构造其实也挺方便的可以指定path。
2.windows下可以下载其他连接器，不一定要用我这种

**Comment by Chinakentgao** [comment]
> 抱歉，你的问题我一时半会没办法回答。我尽可能的回答部分
> 
> 1.burp构造其实也挺方便的可以指定path。 2.windows下可以下载其他连接器，不一定要用我这种

我尝试构造了 但是没有找到path部分怎么写 只有ip跟端口。可否指点一下如何设置

**Comment by veo** [comment]
返回101那个包是升级协议用的，里面包含了path，得构造那个包在burp里的new request填入。你可以抓一个试试

**Comment by Chinakentgao** [comment]
好 我再研究下 谢谢
