### ISSUE TITLE
javax.websocket.DeploymentException

### ISSUE THREAD

**Issue by okoling** [veo/wsMemShell#11]
http://test.com/1.jsp?path=/proxy
```
javax.websocket.DeploymentException: ??????????????WebSocket????????[{1}]????[]?Web????
```
环境
tomcat-7.0.72
java version "1.7.0_79"

**Comment by veo** [comment]
![image](https://user-images.githubusercontent.com/38176360/180119459-283eb5d0-796d-4ff3-ba87-e5e7098bcb74.png)

tomcat-7.0.72 没问题

jdk的话我手上没有1.7，可能是jdk或者其他问题
