### ISSUE TITLE
websocket client

### ISSUE THREAD

**Issue by array0111** [veo/wsMemShell#13]
师傅打扰一下，请问师傅的websocket client是怎么下载的 我在app store上下载不了，换了美区账号也是一样

**Comment by veo** [comment]
> 师傅打扰一下，请问师傅的websocket client是怎么下载的 我在app store上下载不了，换了美区账号也是一样

没什么特别的。我没换账号点了就下了

**Comment by array0111** [comment]
师傅是在appstore里面搜索的吗

**Comment by veo** [comment]
> 师傅是在appstore里面搜索的吗

是的，我也是随便找的一个。其他的应该也可以

**Comment by array0111** [comment]
hh师傅，我是觉得你的web client比较顺滑，其他的像burp，clo那些不太好用。

**Comment by array0111** [comment]
师傅是用的https://itunes.apple.com/us/app/websocket-client/id1399498094?mt=12这个链接吗

**Comment by veo** [comment]
看不到额。是个紫色的图标

**Comment by array0111** [comment]
师傅可以给一下appstore搜索的关键词吗 我这边还是下不了

**Comment by veo** [comment]
怪不得你找不到，好像下架了

**Comment by veo** [comment]
[WebSocket Client.app.zip](https://github.com/veo/wsMemShell/files/9190999/WebSocket.Client.app.zip)

**Comment by array0111** [comment]
谢谢师傅了- v -

**Comment by veo** [comment]
不客气
