### ISSUE TITLE
路径重复注册会导致404

### ISSUE THREAD

**Issue by hosch3n** [veo/wsMemShell#2]
测试环境：

5.15.49-1-MANJARO
Apache Tomcat/9.0.62

需要重启Tomcat才会恢复

**Comment by veo** [comment]
> 测试环境：
> 
> 5.15.49-1-MANJARO Apache Tomcat/9.0.62
> 
> 需要重启Tomcat才会恢复

是的，我知道这个问题，目前是为了介绍思路，给出的代码仅供测试，没加入条件判断代码

**Comment by veo** [comment]
非常感谢提交合并，问题已修复
