### ISSUE TITLE
weblogic12.1.3 报错

### ISSUE THREAD

**Issue by xieshaoping** [veo/wsMemShell#20]
TyrusServerContainer container = (TyrusServerContainer) servletContext.getAttribute(ServerContainer.class.getName());方法在JDK1.8 weblogic12.1.3环境下，wsAddAllContainer.jsp和wscmd.jsp脚本一直返回是空是什么原因？weblogic版本不对吗？

**Comment by veo** [comment]
你赋值path试试呢？有加参数吗

**Comment by xieshaoping** [comment]
![image](https://github.com/veo/wsMemShell/assets/42767703/a2683942-01af-46cf-93ef-cf38ea31db79)
有的

**Comment by veo** [comment]
你可以把报错调出来或者下断点试试

具体哪里出错得自己找找了

**Comment by veo** [comment]
我看出问题来了，要先注入后连接。你得先用 http 注入，再用ws连接到 指定的path
