### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by fengchenzxc** [veo/wsMemShell#6]
jdk1.8.0_221 tomcat8.5.57师傅看看咋回事
![image](https://user-images.githubusercontent.com/41096522/177001616-2d55e95d-453b-405f-af65-773fe4fa671b.png)

**Comment by veo** [comment]
> jdk1.8.0_221 tomcat8.5.57师傅看看咋回事
> ![image](https://user-images.githubusercontent.com/41096522/177001616-2d55e95d-453b-405f-af65-773fe4fa671b.png)

我的锅，刚刚下午改了下代码，又忘了加final

**Comment by veo** [comment]
你再试试

**Comment by fengchenzxc** [comment]
ok了
