### ISSUE TITLE
有没有可能使冰蝎哥斯拉连接ws型shell？

### ISSUE THREAD

**Issue by pipiping** [veo/wsMemShell#8]
好像反序列化时示例代码里删掉TEST方法才能成功运行？
我对websocket不熟，师傅有没有想过ws能不能实现功能比较多的shell管理，或者说冰蝎哥斯拉蚁剑这些工具的内存马能不能在ws下成功生效？

**Comment by veo** [comment]
感谢您的交流提问。

1.反序列化的例子在各个环境下可能需要再修改，我写的比较随意，只是提供思路

2.冰蝎哥斯拉蚁剑这些工具目前的内存马不能在ws下生效，这些马都是基于http协议的。但冰蝎哥斯拉等修改一下源码或者写一个新的连接器升级一下是可以支持websocket马的
